defaults:
  - base_train
  - _self_

# Training iteration
total_samples: 3.0e+8
# minibatch: ???  # decided during runtime

# log
num_history: 500

# wandb
use_wandb: true
watch_model: true

# GPU
# device: ???  # decided during runtime
ddp: true
# ddp_size: ???  # decided during runtime
