defaults:
  - base_train
  - _self_

# Training iteration
total_samples: 1e+8
# minibatch: ???  # decided during runtime

# log
num_history: 1000

# wandb
watch_model: false

# GPU
# device: ???  decided during runtime
ddp: true
ddp_size: 3
# ddp_size: ???  decided during runtime
