defaults:
  - base_train
  - _self_

# Training iteration
total_samples: 1.5e+8
# minibatch: ???  # decided during runtime

# log
num_history: 500

# wandb
watch_model: false

# GPU
# device: ???  # decided during runtime
ddp: true
# ddp_size: ???  # decided during runtime
# ddp_size: 3
