project: caueeg-task1
entity: ipis-mjkim
method: random
program: run_train.py
command:
  - ${env}
  - python
  - ${program}
  - "data=task1"
  - ${args_no_hyphens}

parameters:

  ########
  # Data #
  ########
  data.seq_length:
    values:
      - 1000  # 5 sec
      - 2000  # 10 sec
      - 3000  # 15 sec
      - 4000  # 20 sec

  data.EKG:
    values:
      - O
      - X

  data.photic:
    values:
      - O
      - X

  data.awgn:
    distribution: uniform
    max: 0.12
    min: 0

  data.awgn_age:
    distribution: uniform
    max: 0.3
    min: 0

  data.mgn:
    distribution: uniform
    max: 0.1
    min: 0

  #########
  # Train #
  #########

  train.lr_scheduler_type:
    values:
      - constant_with_decay
      - constant_with_twice_decay
      - transformer_style
      - cosine_decay_with_warmup_half
      - cosine_decay_with_warmup_one_and_half
      # - cosine_decay_with_warmup_two_and_half
      - linear_decay_with_warmup

  #search_multiplier:
  #  values:
  #    - 1.0
  #    - 1.2
  #    - 1.5
  #    - 2.0

  train.weight_decay:
    distribution: log_uniform_values
    max: 0.05
    min: 1e-05

  train.mixup:
    values:
      - 0
      - 0.1
      - 0.2
      - 0.3

  train.criterion:
    values:
      - cross-entropy
      - multi-bce

  #########
  # Model #
  #########

  model:
    values:
      # - 1D-VGG-11
      # - 1D-VGG-13
      # - 1D-VGG-16
      - 1D-VGG-19
      - 1D-ResNet-18
      - 1D-ResNet-50
      # - 1D-ResNet-101
      - 1D-ResNeXt-50
      # - 1D-ResNeXt-101
      - 1D-Wide-ResNet-50
      # - 1D-Wide-ResNet-101
      # - 1D-CNN-Transformer
      # - 2D-VGG-11
      # - 2D-VGG-13
      # - 2D-VGG-16
      - 2D-VGG-19
      - 2D-ResNet-18
      - 2D-ResNet-50
      # - 2D-ResNet-101
      - 2D-ResNeXt-50
      # - 2D-ResNeXt-101
      - 2D-Wide-ResNet-50
      # - 2D-Wide-ResNet-101
      # - 2D-ViT-B-8
      # - 2D-ViT-B-16
      # - 2D-ViT-B-32
      # - 2D-ViT-L-8
      # - 2D-ViT-L-16
      # - 2D-ViT-L-32

  model.fc_stages:
    distribution: int_uniform
    max: 5
    min: 2

  model.use_age:
    values:
      - fc
      - conv

  model.dropout:
    distribution: uniform
    max: 0.5
    min: 0

  model.activation:
    values:
      - relu
      - gelu
      - mish