defaults:
  - data: caueeg-abnormal
  - train: tiny-train
#  - train: base_train
  - model: 1D-VGG-16
  - optional sweep: optional
  - optional ssl: 1D-MAE-B # optional
  - _self_

hydra:
  run:
    dir: local/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}